### ISSUE TITLE
ImportError: cannot import name 'ProgramParameter' from 'qiskit.providers.ibmq.runtime.runtime_program'

### ISSUE THREAD

**Issue by enjis** [Qiskit-Partners/qiskit-dell-runtime#3] opened 2021-12-21 17:03 UTC
Similar issue
https://quantumcomputing.stackexchange.com/questions/5291/importerror-cannot-import-name-quantumprogram-from-qiskit

Installation done with `pip3 install qiskit-dell-runtime`

qiskit version installed **0.19.1**

**Comment by bsantaus** [comment] 2021-12-21 17:19
Hi enjis - had you previously installed qiskit? I believe the requirements for the qiskit-dell-runtime package are qiskit>=0.31.0.

**Comment by enjis** [comment] 2021-12-24 08:01
Hi, No I haven't installed qiskit earlier.
Also, I did a fresh installation.
Below is some warning, I get while doing pip install.
 
`Building wheels for collected packages: qiskit, python-constraint, docplex, dlx, fastdtw, multitasking
  Building wheel for qiskit (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/qiskit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/qiskit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6lhq5cl9
       cwd: /tmp/pip-install-ryrussk_/qiskit/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for qiskit
  Running setup.py clean for qiskit
  Building wheel for python-constraint (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/python-constraint/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/python-constraint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-gsi7t50u
       cwd: /tmp/pip-install-ryrussk_/python-constraint/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for python-constraint
  Running setup.py clean for python-constraint
  Building wheel for docplex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/docplex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/docplex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-n9t88yhl
       cwd: /tmp/pip-install-ryrussk_/docplex/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for docplex
  Running setup.py clean for docplex
  Building wheel for dlx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/dlx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/dlx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r5oaj6d8
       cwd: /tmp/pip-install-ryrussk_/dlx/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for dlx
  Running setup.py clean for dlx
  Building wheel for fastdtw (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/fastdtw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/fastdtw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mjhj4imj
       cwd: /tmp/pip-install-ryrussk_/fastdtw/
  Complete output (8 lines):
  /tmp/pip-install-ryrussk_/fastdtw/setup.py:85: UserWarning: numpy missing, compilation failed. Installing pure python package
    warnings.warn(reason+'compilation failed. Installing pure python package')
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for fastdtw
  Running setup.py clean for fastdtw
  Building wheel for multitasking (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/WORK/QML/.lenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryrussk_/multitasking/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryrussk_/multitasking/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s9zqdcoy
       cwd: /tmp/pip-install-ryrussk_/multitasking/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for multitasking
  Running setup.py clean for multitasking
Failed to build qiskit python-constraint docplex dlx fastdtw multitasking
ERROR: qiskit 0.31.0 has requirement qiskit-ibmq-provider==0.17.0, but you'll have qiskit-ibmq-provider 0.18.3 which is incompatible.
ERROR: qiskit 0.31.0 has requirement qiskit-terra==0.18.3, but you'll have qiskit-terra 0.19.1 which is incompatible.
Installing collected packages: pycparser, cffi, cryptography, charset-normalizer, certifi, idna, urllib3, requests, ntlm-auth, requests-ntlm, numpy, six, python-dateutil, dill, symengine, python-constraint, tweedledum, retworkx, psutil, pbr, stevedore, ply, mpmath, sympy, scipy, qiskit-terra, websocket-client, qiskit-ibmq-provider, qiskit-aer, docplex, dlx, pytz, pandas, more-itertools, inflection, quandl, multitasking, lxml, yfinance, h5py, fastdtw, joblib, threadpoolctl, scikit-learn, qiskit-ignis, qiskit-aqua, qiskit, qiskit-dell-runtime
    Running setup.py install for python-constraint ... done
    Running setup.py install for docplex ... done
    Running setup.py install for dlx ... done
    Running setup.py install for multitasking ... done
    Running setup.py install for fastdtw ... done
    Running setup.py install for qiskit ... done
Successfully installed certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.9 cryptography-36.0.1 dill-0.3.4 dlx-1.0.4 docplex-2.22.213 fastdtw-0.3.4 h5py-3.2.1 idna-3.3 inflection-0.5.1 joblib-1.1.0 lxml-4.7.1 more-itertools-8.12.0 mpmath-1.2.1 multitasking-0.0.10 ntlm-auth-1.5.0 numpy-1.21.5 pandas-1.3.5 pbr-5.8.0 ply-3.11 psutil-5.8.0 pycparser-2.21 python-constraint-1.4.0 python-dateutil-2.8.2 pytz-2021.3 qiskit-0.31.0 qiskit-aer-0.9.1 qiskit-aqua-0.9.5 qiskit-dell-runtime-0.1.1 qiskit-ibmq-provider-0.18.3 qiskit-ignis-0.6.0 qiskit-terra-0.19.1 quandl-3.7.0 requests-2.26.0 requests-ntlm-1.1.0 retworkx-0.10.2 scikit-learn-1.0.1 scipy-1.7.3 six-1.16.0 stevedore-3.5.0 symengine-0.8.1 sympy-1.9 threadpoolctl-3.0.0 tweedledum-1.1.1 urllib3-1.26.7 websocket-client-1.2.3 yfinance-0.1.67`

**Comment by bsantaus** [comment] 2022-01-05 19:04
Hi @enjis - thanks for sharing that. I've just gotten back into the office and had a moment to look into this. Seems I forgot to update the pip package when I pushed new changes up here. It'll be fixed by the end of the day; I'll post again when it's all set.

As for the warnings you're getting there, according to [this stackoverflow post](https://stackoverflow.com/questions/65273035/how-to-fix-error-invalid-command-bdist-wheel) it looks like you just have to run `pip3 install wheel`

Happy New Year!

**Comment by bsantaus** [comment] 2022-01-05 19:11
I've updated the package on pip - try installing the entire package again if you would? It should work as intended now. Thanks for the patience through the holidays!

**Closed by bsantaus** 2022-01-05 19:11 UTC

**Comment by enjis** [comment] 2022-01-13 15:38
Thanks a lot!! I will try this and update it here.
